[package]
name = "hc-actixweb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.1.0" }
actix-files = "0.6.2"
actix-session = { version = "0.7.1", features = ["cookie-session"] }

sqlx = { version = "0.6.1", features = ["sqlite", "runtime-actix-rustls", "any", "macros"] }

serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
futures = "0.3.24"
env_logger = "0.9"
thiserror = "1.0.34"
secrecy = { version = "0.8", features = ["serde"] }
argon2 = { version = "0.4.1", features = ["std"] }

[profile.release]
opt-level = 3
#lto = true
