[package]
name = "hc-axum"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hc-axum"
path = "src/main.rs"

[dependencies]
libhc = { path = "../libhc", features= ["postgres"]}
socketioxide = { version = "0.7.1", features = ["extensions"] }
axum = { version = "0.6.20" }
tokio = { version = "1.34.0", features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.4.4", features = ["cors", "fs"] }
tower = "0.4.13"
tracing-subscriber = "0.3.17"
tracing = "0.1.40"
serde = "1.0.192"
serde_json = "1.0.108"
rand = "0.8.5"
http = "0.2.7"

[profile.release]
opt-level = 3
lto = true
