[package]
name = "hc-axum"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hc-axum"
path = "src/main.rs"

[dependencies]
libhc = { path = "../libhc", features= ["postgres"]}
socketioxide = { version = "0.7.1", features = ["extensions"] }
axum = { version = "0.6.20" , features = ["macros"]}
tokio = { version = "1.34.0", features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.4.4", features = ["cors", "fs"] }
tower = "0.4.13"
tower-sessions = "0.5.0"
tower-cookies = "0.9.0"
tracing-subscriber = "0.3.17"
tracing = "0.1.40"
serde = "1.0.192"
serde_json = "1.0.108"
http = "0.2.7"
uuid = "1.5.0"
sqlx = { version = "0.7.2", features = ["postgres", "runtime-tokio-rustls", "uuid"] }
time = "0.3.30"
secrecy = { version = "0.8.0", features = ["serde"] }
hoplite_verbs_rs = { git = "https://github.com/jeremymarch/hoplite_verbs_rs", version = "0.4.0" }

oauth2 = "4.4.2"
sign-in-with-apple = { git = "https://github.com/jeremymarch/sign-in-with-apple", version = "0.4.1" }

[profile.release]
opt-level = 3
lto = true
